version: '3.8'

services:
  azure-diagram-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - ./diagrams:/app/diagrams
    environment:
      - PYTHONUNBUFFERED=1
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
